import React from 'react';


export const metadata = {
    title: 'Blog | Explore Blogs',
    description: 'Generated by create next app',
  }
const BlogsPage = () => {
    return (
        <div>
           <h3>BlogsPage</h3> 
        </div>
    );
};

export default BlogsPage;